---

- name: /usr/sbin/policy-rc.d作成
  copy: src=policy-rc.d dest=/usr/sbin/policy-rc.d mode=0755

- name: /sbin/initctlの属性判定
  shell: test -L /sbin/initctl
  register: result
  failed_when: result.rc not in [0, 1]

- name: divertする
  shell: dpkg-divert --local --rename --add /sbin/initctl
  when: result.rc != 0

- name: シンボリックリンクにする
  shell: ln -sf /bin/true /sbin/initctl
  when: result.rc != 0

